server:
  port: 8761


eureka:
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 30000
  client:
    registerWithEureka: false
    fetchRegistry: false
    
    
logging:
  level:
    com.netflix: TRACE